server:
  port : 9091
  #MySQL Connectivity
  spring:
    datasource :
      url : jdbc:mysql://localhost:3306/detailscustomer
      username : root
      password : Manager
      driver-class-name : com.mysql.cj.jdbc.Driver

    jpa:
      show-sql : true
      database-platform : org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: update

